image: Ubuntu1804 # образ для сборки
stack: node 12 # окружение
branches:
  only:
    - master # ветка git
cache: node_modules # кеширование
install:
  - yarn # команда установки зависимостей
build: off
build_script:
  - yarn run build # команда сборки
